In [14]:
import torch
checkpoint = torch.load('0001_CausalCNNEncoder_HiRID_checkpoint_0.tar', map_location=torch.device('cpu'))

print(checkpoint['data_type'])
print(checkpoint['encoder_type'])
print(checkpoint['encoder_hyper_params'])
print(checkpoint['learn_encoder_hyper_params'])
print(checkpoint['classification_hyper_params'])

print(checkpoint['pretrain_hyper_params'])
print(checkpoint['unique_id'])
print(checkpoint['unique_name'])


checkpoint['learn_encoder_hyper_params']['ACF_PLUS'] = False
checkpoint['learn_encoder_hyper_params']['ADF'] = True
checkpoint['encoder_hyper_params']['in_channels'] = 18
checkpoint['encoder_hyper_params']['encoding_size'] = 6
torch.save(checkpoint, '0001_CausalCNNEncoder_HiRID_checkpoint_0_tnc.tar')

HiRID
CausalCNNEncoder
{'in_channels': 36, 'channels': 4, 'depth': 1, 'reduced_size': 2, 'encoding_size': 10, 'kernel_size': 2, 'window_size': 12, 'device': 'cpu'}
{'window_size': 12, 'w': 0.05, 'batch_size': 30, 'lr': 5e-05, 'decay': 0.0005, 'mc_sample_size': 6, 'n_epochs': 150, 'data_type': 'HiRID', 'n_cross_val_encoder': 1, 'cont': True, 'ETA': 4, 'ADF': False, 'ACF': False, 'ACF_PLUS': True, 'ACF_nghd_Threshold': 0.6, 'ACF_out_nghd_Threshold': 0.1, 'device': 'cpu'}
{'n_cross_val_classification': 3}
{}
0001
0001_CausalCNNEncoder_HiRID


In [15]:
checkpoint = torch.load('0001_CausalCNNEncoder_HiRID_checkpoint_0_tnc.tar', map_location=torch.device('cpu'))
print(checkpoint['encoder_hyper_params'])
print(checkpoint['learn_encoder_hyper_params'])
print(checkpoint['pruning_mask'])
print(checkpoint['pruned_encoding_size'])

{'in_channels': 18, 'channels': 4, 'depth': 1, 'reduced_size': 2, 'encoding_size': 6, 'kernel_size': 2, 'window_size': 12, 'device': 'cpu'}
{'window_size': 12, 'w': 0.05, 'batch_size': 30, 'lr': 5e-05, 'decay': 0.0005, 'mc_sample_size': 6, 'n_epochs': 150, 'data_type': 'HiRID', 'n_cross_val_encoder': 1, 'cont': True, 'ETA': 4, 'ADF': True, 'ACF': False, 'ACF_PLUS': False, 'ACF_nghd_Threshold': 0.6, 'ACF_out_nghd_Threshold': 0.1, 'device': 'cpu'}
tensor([False,  True, False, False,  True,  True,  True,  True,  True,  True])


KeyError: 'pruned_encoding_size'

In [10]:
import torch
x = torch.randn(3, 4)
print(x)
mask = x[0].ge(0.5)
print(mask)
l = int(torch.sum(mask))
print(l)
y = torch.masked_select(x, mask).reshape(3,l)
print(y)

tensor([[-0.1570,  1.2607,  0.5541, -0.3365],
        [ 0.3685,  1.1806,  1.7348, -0.8269],
        [ 1.0051, -0.7403,  1.0233,  1.3354]])
tensor([False,  True,  True, False])
2
tensor([[ 1.2607,  0.5541],
        [ 1.1806,  1.7348],
        [-0.7403,  1.0233]])
